---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:498a000f370d8c37927118ed80afe8adc38d1edcbfc071627d17b25c88efcab0
    command: |
      sh /var/lib/busybox/run.sh
    volumes:
      - ./run.sh:/var/lib/busybox/run.sh:ro
      - /etc/machine-id:/var/lib/busybox/machine-id:ro      