---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
    command: |
      sh /var/lib/busybox/run.sh
    volumes:
      - ./run.sh:/var/lib/busybox/run.sh:ro
      - /etc/machine-id:/var/lib/busybox/machine-id:ro      