---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f
    volumes:
      - /mnt/busybox:/srv/busybox
      - ./commands.sh:/var/lib/commands.sh:ro
    command: |
      sh /var/lib/commands.sh
          