---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:ab33eacc8251e3807b85bb6dba570e4698c3998eca6f0fc2ccb60575a563ea74
    volumes:
      - /mnt/busybox:/srv/busybox
    command: |
      echo "Hello from busybox at $(date)" >> /srv/busybox/log.txt && cat /srv/busybox/log.txt
    