---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vpc-hpcrs.hpse.ibm.com
spec:
  group: hpse.ibm.com
  names:
    kind: HyperProtectContainerRuntimeVPC
    plural: vpc-hpcrs
    singular: vpc-hpcr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                contract:
                  type: string
                subnetID:
                  type: string
                profileName:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
                targetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
            status:
              type: object
              properties:
                status:
                  type: integer
                description:
                  type: string
                metadata:
                  type: object
                  additionalProperties: true
              additionalProperties: true
          required:
            - spec
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onprem-hpcrs.hpse.ibm.com
spec:
  group: hpse.ibm.com
  names:
    kind: HyperProtectContainerRuntimeOnPrem
    plural: onprem-hpcrs
    singular: onprem-hpcr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                contract:
                  type: string
                imageURL:
                  type: string
                storagePool:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
                targetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
                diskSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
                networkSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
            status:
              type: object
              properties:
                status:
                  type: integer
                description:
                  type: string
                metadata:
                  type: object
                  additionalProperties: true
              additionalProperties: true
          required:
            - spec
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onprem-datadisks.hpse.ibm.com
spec:
  group: hpse.ibm.com
  names:
    kind: HyperProtectContainerRuntimeOnPremDataDisk
    plural: onprem-datadisks
    singular: onprem-datadisk
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                storagePool:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
                targetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
            status:
              type: object
              properties:
                status:
                  type: integer
                description:
                  type: string
                metadata:
                  type: object
                  additionalProperties: true
              additionalProperties: true
          required:
            - spec
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onprem-datadiskrefs.hpse.ibm.com
spec:
  group: hpse.ibm.com
  names:
    kind: HyperProtectContainerRuntimeOnPremDataDiskRef
    plural: onprem-datadiskrefs
    singular: onprem-datadiskref
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                volumeName:
                  type: string
                storagePool:
                  type: string
                targetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
              required:
                - volumeName
                - targetSelector
            status:
              type: object
              properties:
                status:
                  type: integer
                description:
                  type: string
                metadata:
                  type: object
                  additionalProperties: true
              additionalProperties: true
          required:
            - spec
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onprem-networkrefs.hpse.ibm.com
spec:
  group: hpse.ibm.com
  names:
    kind: HyperProtectContainerRuntimeOnPremNetworkRef
    plural: onprem-networkrefs
    singular: onprem-networkref
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                networkName:
                  type: string
                targetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          value:
                            type: array
                            items:
                              type: string
              required:
                - networkName
                - targetSelector
            status:
              type: object
              properties:
                status:
                  type: integer
                description:
                  type: string
                metadata:
                  type: object
                  additionalProperties: true
              additionalProperties: true
          required:
            - spec
