---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:f64ff79725d0070955b368a4ef8dc729bd8f3d8667823904adcb299fe58fc3da
    volumes:
      - /mnt/busybox:/srv/busybox
      - ./commands.sh:/var/lib/commands.sh:ro
    command: |
      sh /var/lib/commands.sh
          