---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:d82f458899c9696cb26a7c02d5568f81c8c8223f8661bb2a7988b269c8b9051e
    volumes:
      - /mnt/busybox:/srv/busybox
      - ./commands.sh:/var/lib/commands.sh:ro
    command: |
      sh /var/lib/commands.sh
          