---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c91053da9979728cceb1dc68
    volumes:
      - /mnt/busybox:/srv/busybox
      - ./commands.sh:/var/lib/commands.sh:ro
    command: |
      sh /var/lib/commands.sh
          