---
version: '3.0'
services:
  busybox:
    image: docker.io/library/busybox@sha256:2376a0c12759aa1214ba83e771ff252c7b1663216b192fbe5e0fb364e952f85c
    volumes:
      - /mnt/busybox:/srv/busybox
      - ./commands.sh:/var/lib/commands.sh:ro
    command: |
      sh /var/lib/commands.sh
          